### ISSUE TITLE
ulong doesn't name a type

### ISSUE THREAD

**Issue by M1S2** [tedtoal/XPT2046_Touchscreen_TT#3]
I'm using your great library with platformio.
There is the following compiler error:

```
.pio\libdeps\example_touch_calibration\XPT2046_Touchscreen_TT\src/TS_Display.h:167:3: error: 'ulong' does not name a type; did you mean 'long'?
   ulong _msTime;
   ^~~~~
   long
```

If I change the type to unsigned long manually and recompile, everything works.

**Comment by tedtoal** [comment]
Great, I’m glad to hear its working well for you.

Thanks for finding and reporting the bug!!  The correct type should have been uint32_t instead of ulong.  I have changed the code and issued a new release, which should be picked up by the Arduino system in less than 24 hours.

Ted Toal


On Dec 2, 2024, at 9:57 AM, M1S2 ***@***.***> wrote:



I'm using your great library with platformio.
There is the following compiler error:

.pio\libdeps\example_touch_calibration\XPT2046_Touchscreen_TT\src/TS_Display.h:167:3: error: 'ulong' does not name a type; did you mean 'long'?
   ulong _msTime;
   ^~~~~
   long


If I change the type to unsigned long manually and recompile, everything works.

**Comment by M1S2** [comment]
Thank's for your very fast bugfix. It works like a charm now using v1.8.1.
